# サイトの基本情報
baseURL = "https://ipblog.pages.dev/"
languageCode = "ja"
title = "実務者のための知財法務"
theme = "PaperMod"
googleAnalytics = "G-GK6P50PLB9"

# パーマリンク設定
[permalinks]
post = "/post/:year/:month/:day/:contentbasename/"

[params.homeInfoParams]
  Title = "実務者のための知財法務"
  Content = "日々の業務で得た知見をもとに、知財や契約に関する内容を中心とした記事を、備忘録としてまとめています。<br>あくまで一知財部員の主観も含まれた記事として、参考程度に見て頂けると有り難いです。"

[params]
  defaultTheme = "light"      # ダークモードを使わない場合は"light"
  ShowShareButtons = false    # 各記事の下部に表示するshareボタンの表示の有無
  ShowReadingTime = false      # 各記事の読み終わるまでの時間を表記するかどうか
  ShowPostNavLinks = true     # 前後のポストへのNavigationを表示するかどうか
  ShowBreadCrumbs = true      # 各記事の階層関係を表示するかどうか
  ShowCodeCopyButtons = true  # 記事内のコードをコピーするボタンを表示するかどうか
  ShowToc = true              # TOCを表示するかどうか
  TocOpen = true              # 初期で展開しておくかどうか
  sortPostBy = "date"

# ファビコン設定
[params.assets]
  favicon = "/assets/images/ip_favicon.ico"
  favicon16x16 = "/assets/images/ip_favicon_16.png"
  favicon32x32 = "/assets/images/ip_favicon_32.png"
  apple_touch_icon = "/assets/images/ip_apple-touch-icon.png"
  safari_pinned_tab = "/ip_safari-pinned-tab.svg"

[params.fuseOpts]
  isCaseSensitive = false # 大文字小文字を識別するかどうか
  shouldSort = true # スコアで記事をソートするかどうか
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ] # 記事ごとの検索対象となる要素（ここに含めた要素の中の文字を検索する）

[outputs]
  home = [ "HTML", "RSS", "SITEMAP", "JSON" ]

# メニュー設定
[menu]
[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "categories"
  name = "Categories"
  url = "/categories/"
  weight = 2

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 3

[[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/search/"
  weight = 4

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 5

[[menu.main]]
  identifier = "privacy"
  name = "Privacy"
  url = "/privacy/"
  weight = 6

  [[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 7

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# タクソノミー（分類）
[taxonomies]
  tag = "tags"
  category = "categories"


[related]
threshold = 0
includeNewer = true
toLower = false

[[related.indices]]
name = "tags"
weight = 100

[[related.indices]]
name = "categories"
weight = 80

[[related.indices]]
name = "title"
weight = 20

[[related.indices]]
name = "keywords"
weight = 10

# サイトマップ
[sitemap]
  changefreq = "weekly"
  priority = 0.5

enableRobotsTXT = false

