baseURL = "https://ipblog.pages.dev/"
languageCode = "ja"
title = "実務者のための知財法務"
theme = "PaperMod"
googleAnalytics = ""

[permalinks]
post = "/post/:year/:month/:day/:contentbasename/"

[params.homeInfoParams]
  Title = "実務者のための知財法務"
  Content = "日々の業務で得た知見をもとに、知財や契約に関する内容を中心とした記事を、備忘録としてまとめています。<br>あくまで一知財部員の主観も含まれた記事として、参考程度に見て頂けると有り難いです。"

[params]
  defaultTheme = "light"    # ダークモードを使わない場合は"light"
  ShowShareButtons = false
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = true
  sortPostBy = "date"

[params.assets]
  favicon = "/assets/images/ip_favicon.ico"
  favicon16x16 = "/assets/images/ip_favicon_16.png"
  favicon32x32 = "/assets/images/ip_favicon_32.png"
  apple_touch_icon = "/assets/images/ip_apple-touch-icon.png"

[params.fuseOpts]
  isCaseSensitive = false # 大文字小文字を識別するかどうか
  shouldSort = true # スコアで記事をソートするかどうか
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ] # 記事ごとの検索対象となる要素（ここに含めた要素の中の文字を検索する）

[outputs]
  home = [ "HTML", "RSS", "SITEMAP", "JSON" ]

[menu]
[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "categories"
  name = "Categories"
  url = "/categories/"
  weight = 2

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 3

[[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/search/"
  weight = 4

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 5

[[menu.main]]
  identifier = "privacy"
  name = "Privacy"
  url = "/privacy/"
  weight = 6

  [[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "https://forms.gle/nEdcyw1FDb2HKvqi6"
  weight = 7

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"
  category = "categories"


[related]
threshold = 0
includeNewer = true
toLower = false

[[related.indices]]
name = "tags"
weight = 100

[[related.indices]]
name = "categories"
weight = 80

[[related.indices]]
name = "title"
weight = 20

[[related.indices]]
name = "keywords"
weight = 10


enableRobotsTXT = true

